version: '3.8'

networks:
  petland_network:
    driver: bridge

services:
  postgres:
    image: postgres:15
    container_name: ${DB_NAME}
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - petland_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - petland_network
