package com.petland.modules.petCare.dtos;

import com.petland.common.entity.Address;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

@Builder
@Schema(description = "Response DTO representing pet care services.")
public record PetCareResponseDTO(

        @Schema(description = "Unique identifier of the pet care service.", example = "a1b2c3d4-e5f6-7g8h-9i0j-abcdef123456")
        UUID id,

        @Schema(description = "Unique identifier of the pet.", example = "c2d3b4a5-e6f7-8g9h-0i1j-abcdef987654")
        UUID petId,

        @Schema(description = "Unique identifier of the customer.", example = "d3c2a1b4-e5f6-7g8h-9i0j-abcdef654321")
        UUID customerId,

        @Schema(description = "Unique identifier of the employee responsible.", example = "b4c3a2d1-e6f7-8g9h-0i1j-abcdef321654")
        UUID employeeId,

        @Schema(description = "List of details about the pet care services.")
        List<PetCareDetailsResponseDTO> detailsResponseDTO,

        @Schema(description = "Total revenue generated by the service.", example = "200.50")
        BigDecimal totalRevenue,

        @Schema(description = "Total profit from the service.", example = "80.25")
        BigDecimal totalProfit,

        @Schema(description = "Total operating cost of the service.", example = "120.25")
        BigDecimal totalCostOperating,

        @Schema(description = "Date and time of the service.", example = "2025-09-07T14:00:00")
        LocalDateTime serviceDate,

        @Schema(description = "Location where the service was performed.")
        Address location
) {}
