package com.petland.modules.vaccination.enums;

public enum VaccineType {
    RABIES,
    DISTEMPER,
    PARVOVIRUS,
    ADENOVIRUS,
    PARAINFLUENZA,
    BORDETELLA,
    LEPTOSPIROSIS,
    CANINE_CORONAVIRUS,
    LYME_DISEASE,
    FELINE_RABIES,
    FELINE_PANLEUKOPENIA,
    FELINE_CALICIVIRUS,
    FELINE_HERPESVIRUS,
    FELINE_LEUKEMIA,
    FELINE_IMMUNODEFICIENCY,
    FELINE_CHLAMYDIA
}
